### PR TITLE
Fix exceptions if "enableTwigStrictVariables" is set to true

### PR DESCRIPTION
**Pull request by xitara**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Why are those variables not defined?

**Comment by xitara** [comment]
width has no field-definition, color and icon can be empty

**Comment by LukeTowers** [comment]
color and icon should both still be defined

**Comment by xitara** [comment]
yes, but if color ist an empty string, it results in `style="background-color: ;"` and `{% if data.config.icon %}` compares against NULL, so if data.config.icon ist an empty string, the i-element will be displayed as `<i class="fas  mr-2"></i>` but it should not displayed without an icon, I think

**Review by LukeTowers — APPROVED** [review]

**Pull request merged**
