### PR TITLE
Display block name on non collapsed blocks in formwidget

### PR DESCRIPTION
**Pull request by xitara**
Now the user can see the blockname  on unfolded blocks to identify the right block to change content

### CODE REVIEW

**Comment by LukeTowers** [comment]
@xitara could you post a before/after screenshot?

**Comment by xitara** [comment]
before:
Bildschirmfoto_2023-03-09_21-10-51

after:
Bildschirmfoto_2023-03-09_21-10-09

the red arrows show the changes

**Comment by LukeTowers** [comment]
How does it look when collapsed? This is why the core blocks provided by this plugin all have "section" fields at the top of their field configs to act as the block titles in the backend.

**Comment by xitara** [comment]
Collapsed it's look like before, no changes.
Yes you can do it with a section. My thoughts are that this work can be saved with this little patch

**Comment by LukeTowers** [comment]
Hmm, my main concerns at this point would be: 

1. The existing demo blocks all use the section approach, so either we'd implement this PR and remove the sections so that they aren't doubling up, or we just say "Use sections" and don't merge this.
2. I'm not a fan of using `<h*>` tags purely for visuals, they have semantically meaning and slapping them in the middle of the page's markup can cause issues, especially with accessibility. Are you able to switch it to a `<strong>` or something that's more explicitly styled rather than relying on the implicit styling of h tags?

**Comment by xitara** [comment]
I think, we use sections and don't merge, this is the more flexible solution

**Pull request closed without merging**
